# Generated by Django 3.0.1 on 2019-12-24 22:04

from datetime import datetime
from django.db import migrations


def create_sample_package(apps, schema_editor):
    Package = apps.get_model('post', 'Package')
    p = Package(
        id=42,
        sender_name="Ktulhu",
        receiver_name="H. P. Lovecraft",
        tracking_number="123",
        address_from="R'lyeh",
        address_to="Providence, Rhode Island, U.S.",
        status='TR',
        price=42,
        value=42,
        weight=42,
        accepted_at=datetime.now(),
        delivered_at=None,
    )
    p.save()


def delete_sample_package(apps, schema_editor):
    Package = apps.get_model('post', 'Package')
    Package.objects.filter(id=42).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sample_package, delete_sample_package)
    ]

