# Generated by Django 3.0.1 on 2019-12-25 20:19

from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.db.migrations import RunPython
from django.contrib.auth.models import User


def create_admin(apps, schema_builder):
    user = User.objects.create_user('admin', 'admin@example.com', 'admin')
    user.save()


def delete_admin(apps, schema_builder):
    User.objects.filter(username='admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191224_2204'),
    ]

    operations = [
        RunPython(create_admin, delete_admin)
    ]
